package com.upiledger.payments;

import com.upiledger.accounts.*; import com.upiledger.idempotency.*; import com.upiledger.ledger.*; import org.junit.jupiter.api.*; import org.mockito.*; import java.math.BigDecimal; import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
class PaymentServiceTest {
 @Test void createIsIdempotentForSameKeyAndPayload(){var txRepo=mock(PaymentTransactionRepository.class);var bal=mock(AccountBalanceRepository.class);var hold=mock(AccountHoldRepository.class);var ledger=mock(LedgerPostingService.class);var idem=mock(IdempotencyKeyRepository.class);UUID p=UUID.randomUUID(),q=UUID.randomUUID(),id=UUID.randomUUID();var tx=new PaymentTransaction("ext-1",p,q,new BigDecimal("500"),"INR");when(idem.findByIdempotencyKey("key-1")).thenReturn(Optional.empty()); when(txRepo.findByExternalTxnId("ext-1")).thenReturn(Optional.empty()); when(txRepo.save(any())).thenAnswer(inv->inv.getArgument(0)); when(idem.save(any())).thenAnswer(inv->inv.getArgument(0));
  PaymentService s=new PaymentService(txRepo,bal,hold,ledger,idem);var result=s.create(new PaymentService.CreatePaymentCommand("ext-1",p,q,new BigDecimal("500"),"INR"),"key-1");assertNotNull(result);verify(txRepo).save(any(PaymentTransaction.class));verify(idem, times(2)).save(any(IdempotencyKey.class)); }
 @Test void authorizeReservesAvailableBalanceAndCreatesHold(){var txRepo=mock(PaymentTransactionRepository.class);var balRepo=mock(AccountBalanceRepository.class);var holdRepo=mock(AccountHoldRepository.class);var ledger=mock(LedgerPostingService.class);var idem=mock(IdempotencyKeyRepository.class);UUID p=UUID.randomUUID(),q=UUID.randomUUID(),id=UUID.randomUUID();var tx=new PaymentTransaction("ext-2",p,q,new BigDecimal("500"),"INR");var balance=new AccountBalance(p,"INR");balance.applyCredit(new BigDecimal("1000"));when(txRepo.findById(id)).thenReturn(Optional.of(tx));when(balRepo.findByIdForUpdate(p)).thenReturn(Optional.of(balance));when(balRepo.save(any())).thenAnswer(inv->inv.getArgument(0));when(holdRepo.save(any())).thenAnswer(inv->inv.getArgument(0));when(txRepo.save(any())).thenAnswer(inv->inv.getArgument(0)); // id cannot be set in unit entity, so service lookup is not exercised with persisted ID
  // use reflection to set generated id for a deterministic state-machine test
  try{var field=PaymentTransaction.class.getDeclaredField("id");field.setAccessible(true);field.set(tx,id);}catch(Exception e){throw new RuntimeException(e);} PaymentService s=new PaymentService(txRepo,balRepo,holdRepo,ledger,idem);var out=s.authorize(id);assertEquals(TransactionStatus.AUTHORIZED,out.getStatus());assertEquals(new BigDecimal("500"),balance.getAvailableBalance());verify(holdRepo).save(any(AccountHold.class)); }
 @Test void invalidTransitionIsRejected(){var txRepo=mock(PaymentTransactionRepository.class);UUID id=UUID.randomUUID();UUID p=UUID.randomUUID(),q=UUID.randomUUID();var tx=new PaymentTransaction("ext-3",p,q,new BigDecimal("10"),"INR");try{var f=PaymentTransaction.class.getDeclaredField("id");f.setAccessible(true);f.set(tx,id);}catch(Exception e){throw new RuntimeException(e);}when(txRepo.findById(id)).thenReturn(Optional.of(tx));var s=new PaymentService(txRepo,mock(AccountBalanceRepository.class),mock(AccountHoldRepository.class),mock(LedgerPostingService.class),mock(IdempotencyKeyRepository.class));assertThrows(InvalidPaymentStateException.class,()->s.settle(id));}
}
