spring:
  application:
    name: upi-ledger

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/upiledger}
    username: ${DB_USERNAME:upiledger}
    password: ${DB_PASSWORD:upiledger}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      enable-idempotence: true

upiledger:
  kafka:
    topics:
      payment-lifecycle: ${KAFKA_TOPIC_PAYMENT_LIFECYCLE:upiledger.payment.lifecycle.v1}
      ledger-entry-posted: ${KAFKA_TOPIC_LEDGER_ENTRY_POSTED:upiledger.ledger.entry.posted.v1}
      payment-settled: ${KAFKA_TOPIC_PAYMENT_SETTLED:upiledger.payment.settled.v1}
      payment-failed: ${KAFKA_TOPIC_PAYMENT_FAILED:upiledger.payment.failed.v1}
      payment-reversed: ${KAFKA_TOPIC_PAYMENT_REVERSED:upiledger.payment.reversed.v1}
      dlq: ${KAFKA_TOPIC_DLQ:upiledger.dlq.v1}
  outbox:
    publisher:
      fixed-delay-ms: ${OUTBOX_PUBLISHER_FIXED_DELAY_MS:1000}
      retry-delay-ms: ${OUTBOX_PUBLISHER_RETRY_DELAY_MS:5000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

server:
  error:
    include-message: never
    include-binding-errors: never
